/**
 * @author  tongh
 * @date  2022/7/19 4:06 下午
 */
package common

import (
	"fmt"
	"testing"
	"time"
)

func TestFunc(t *testing.T) {
	s := "{\"conn_no\":\"18330e66f93f888346d857f71e6b2c6b\",\"method\":\"uploadFile\",\"data\":\"eyJGaWxlTmFtZSI6IjAwOTJkMzEzNDY3NWU3OGRkYThhZDA5OGE0YjYzNTA3XzIwMjAwNDA2MjMzMjM0LnNncyIsIkZpbGVTaXplIjo1MTIwMCwiRmlsZU5vIjowLCJDb250ZW50IjoiQlRNdU9DNHlDVk5uYzAxdlltbHNaUUFBQUFESUFnQUFLTTczejhTendzcXIwdDBBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBVVpYZ3dNVEExTURZM01qZzFOblJ4ZFM1a2MzQUFBakUyQVRReU1ESXdNRFF3TmpJek16SXpOQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB"
	fmt.Println(len([]byte(s)))
	return
	tt := 3 * time.Second
	tick := time.NewTicker(tt)
	fmt.Println(time.Now().Format("2006-01-02 15:04:05"), "start")
	tick.Stop()
	time.Sleep(5 * time.Second)
	tick.Reset(tt)
	fmt.Println(time.Now().Format("2006-01-02 15:04:05"), "reset")
	for true {
		select {
		case data := <-tick.C:
			fmt.Println(time.Now().Format("2006-01-02 15:04:05"), "get", data.Format("2006-01-02 15:04:05"))

		}
	}
}
